spring:
  profiles: development
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
    username: root
    password: root
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group-id
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer        
aws:
  s3:
    bucket: ${bucketname}
    access: ${accesskey}
    secret: ${secretkey}
    region: ${region}
server:
  port: 8080
  
---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
    username: ${dbuser}
    password: ${dbpassword}
server:
  port: 8080
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false
    username: ${dbuser}
    password: ${dbpassword}
server:
  port: 8080